
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[build]
  publish = "public" # or your build output folder
  command = "npm run build"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.20.3" # use your project's required Node version